import { RefObject } from 'react'
import { usePlatformStore } from '../../../stores/platformStore'
import { VolumesSummary } from './VolumesSummary'
import { ReagentChecklist } from './ReagentChecklist'
import { BeadRegionList } from './BeadRegionList'
import { PrepInstructions } from './PrepInstructions'

interface PrepSheetProps {
  /** Ref for react-to-print integration */
  contentRef: RefObject<HTMLDivElement>
}

/**
 * Printable preparation sheet composing all prep sections
 * Designed for both screen preview and physical printing
 * Use with react-to-print to enable print functionality
 */
export function PrepSheet({ contentRef }: PrepSheetProps) {
  const { getSelectedPlatform } = usePlatformStore()
  const selectedPlatform = getSelectedPlatform()

  const platformName = selectedPlatform?.name ?? 'Unknown Platform'
  const currentDate = new Date().toLocaleDateString('en-US', {
    weekday: 'long',
    year: 'numeric',
    month: 'long',
    day: 'numeric'
  })

  return (
    <div
      ref={contentRef}
      className="p-6 print:p-4 bg-white min-h-full"
    >
      {/* Header */}
      <header className="mb-6 print:mb-4 border-b border-gray-200 pb-4 print:pb-3">
        <h1 className="text-2xl font-bold text-gray-900 print:text-xl">
          Immunoplex Assay Prep Sheet
        </h1>
        <div className="mt-2 flex flex-wrap gap-x-6 gap-y-1 text-sm text-gray-600 print:text-xs">
          <p>
            <span className="font-medium">Platform:</span> {platformName}
          </p>
          <p>
            <span className="font-medium">Date:</span> {currentDate}
          </p>
        </div>
      </header>

      {/* Volume Summary Section */}
      <section className="mb-6 print:mb-4 print:break-inside-avoid">
        <VolumesSummary />
      </section>

      {/* Reagent Checklist Section */}
      <section className="mb-6 print:mb-4 print:break-inside-avoid">
        <ReagentChecklist />
      </section>

      {/* Preparation Instructions Section */}
      <section className="mb-6 print:mb-4">
        <PrepInstructions />
      </section>

      {/* Bead Region List Section */}
      <section className="print:break-before-auto">
        <BeadRegionList />
      </section>

      {/* Footer */}
      <footer className="mt-8 pt-4 border-t border-gray-200 text-xs text-gray-400 print:mt-6 print:pt-3">
        <p>Generated by Immunoplex Assay Calculator</p>
        <p className="mt-1">
          Verify all calculations before proceeding. Consult kit documentation for protocol details.
        </p>
      </footer>
    </div>
  )
}
